[project]
name = "linkdin-technical-project-post-writer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "gitpython>=3.1.62",
    "langchain-google-genai>=4.4.0",
    "langgraph>=1.2.11",
    "langsmith>=0.12.4",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
    "streamlit>=1.63.0",
]
